### ISSUE TITLE
requirement for youtube-dl outdated

### ISSUE THREAD

**Issue by kjyv** [crisbal/Album-Splitter#13]
The specified version is not compatible to youtube anymore. Using the current youtube-dl (2016-10-31), I can download files successfully. Maybe it makes sense to not specify the version explicitly in requirements.txt

**Comment by crisbal** [comment]
I updated the requirements in the latest update.

**Comment by mmccollow** [comment]
I had the same issue and fixed it by running `pip install -U youtube-dl`. YouTube is a moving target, so I'd second OP's recommendation that the requirements/prod.txt file not explicitly specify a version for youtube-dl. It should always install the latest version.
