### ISSUE TITLE
Add track number to file names

### ISSUE THREAD

**Issue by kjyv** [crisbal/Album-Splitter#14]
The output files are currently unsorted even though the tags are correct.
Alternatively, a custom file name string would be even better.

**Comment by kjyv** [comment]
As this is such a small change I won't create a pull request.
The filenames are properly sorted by replacing split.py:39 with:
`track_path = '{}/{:02d} - {}.mp3'.format(FOLDER, index+1, track)`

**Comment by crisbal** [comment]
Hey, sorry for not getting back to you on the first message. 

Thanks for the fix, create the PR if you want. In the next days I will get back on the project to fix a few of these things.

**Comment by crisbal** [comment]
I fixed it, enjoy!
