### ISSUE TITLE
Improve codebase

### ISSUE THREAD

**Issue by JohnMoutafis** [crisbal/album-splitter#17]
Let's work on those before we begin to explore and expand. 

- [ ] Improve `split.py` code structure
- [ ] Refactor `split.py` for better maintainability
- [ ] Make code DRY
- [ ] Improve overall code structure

**Comment by crisbal** [comment]
One good thing would be to separate the "interface"/"command line interface" from the part of the code that does the heavy work (splitting, tagging, ...), just like you started doing in #18. 

This way one could build another interface for the project without much work to do.

**Comment by JohnMoutafis** [comment]
That would be good indeed @crisbal
