### ISSUE TITLE
Change project name

### ISSUE THREAD

**Issue by JohnMoutafis** [crisbal/album-splitter#21]
We should change the project name to `album_splitter` or `album-splitter` in order to comply to python naming standards.
 
Not something serious, just bugging me :stuck_out_tongue:

**Comment by crisbal** [comment]
`album-splitter` seems good, similar to `youtube-dl`

**Comment by crisbal** [comment]
Done!

**Comment by crisbal** [comment]
Yeah much better now

**Comment by JohnMoutafis** [comment]
Indeed!!
