### ISSUE TITLE
Example fails

### ISSUE THREAD

**Issue by morkor** [crisbal/album-splitter#24]
Dear crisbal,

thanks for providing this. I have an issue though executing the example you provide. I followed the installation steps, skipping the virtualenv ones, and installation seems successful. Running the example I got: 
python split.py -yt https://www.youtube.com/watch?v=p_uqD4ng9hw --metadata https://en.wikipedia.org/wiki/Dogs_Eating_DogsTraceback (most recent call last):
  File "split.py", line 5, in <module>
    from queue import Queue
ImportError: No module named queue

from which I cannot make much sense.
Best,
morkor

**Comment by crisbal** [comment]
Hey, thanks for reporting the issue.

Try using `python3` instead of `python` for executing the script. It requires python 3 and usually by default python is python 2.

Also you should install the requirements using pip3 which installs python 3 version of the modules.

**Comment by morkor** [comment]
Yes, installing requirements using pip3 and then executing the script with python3 works fine! thanks!
