### ISSUE TITLE
Won't split large files (length > 10h) on Windows 10 64bit 16GB RAM

### ISSUE THREAD

**Issue by kamisori** [crisbal/album-splitter#25]
I got an audiobook here and because it is cumbersome to listen to it in one big chunk, I decided to split it into its chapters.
I attached the tracks list and the first broken file.
All files prior to chapter 13 are fine, all files after including ch13 are broken.
The following is the commandline output.

PS D:\#work#\album-splitter> python.exe .\split.py -mp3 '.\Masters of Doom- How Two Guys Created an Empire and Transform
ed Pop Culture.mp3' -t .\tracks.txt
Parsing .\tracks.txt
Tracks file parsed
Loading audio file
Audio file loaded
Starting to split
        1) 00_Introduction
                Tagging
        2) 01_Chapter_01
                Tagging
        3) 02_Chapter_02
                Tagging
        4) 03_Chapter_03
                Tagging
        5) 04_Chapter_04
                Tagging
        6) 05_Chapter_05
                Tagging
        7) 06_Chapter_06
                Tagging
        8) 07_Chapter_07
                Tagging
        9) 08_Chapter_08
                Tagging
        10) 09_Chapter_09
                Tagging
        11) 10_Chapter_10
                Tagging
        12) 11_Chapter_11
                Tagging
        13) 12_Chapter_12
                Tagging
        14) 13_Chapter_13
                Tagging
        15) 14_Chapter_14
                Tagging
        16) 15_Chapter_15
                Tagging
        17) 16_Chapter_16
                Tagging
        18) 17_Epilog
                Tagging
        19) 18_Afterword
                Tagging
        20) 19_Authors_Note
                Tagging
All Done

[tracks.txt](https://github.com/crisbal/album-splitter/files/1470208/tracks.txt)
[13_Chapter_13.zip](https://github.com/crisbal/album-splitter/files/1470214/13_Chapter_13.zip)

**Comment by kamisori** [comment]
Next I edited the trackslist to only include Chapters from 12 onwards, the resulting files were all broken.
I let the script print(start, end, duration) in the function split_song.
I guess pydub is at fault.

This is what was printed:

PS D:\#work#\album-splitter> python.exe .\split.py -mp3 '.\Masters of Doom- How Two Guys Created an Empire and Transform
ed Pop Culture.mp3' -t .\tracks.txt
Parsing .\tracks.txt
Tracks file parsed
Loading audio file
Audio file loaded
Starting to split
        1) 12_Chapter_12
30424000 34015000 3591000
                Tagging
        2) 13_Chapter_13
34015000 37277000 3262000
                Tagging
        3) 14_Chapter_14
37277000 39984000 2707000
                Tagging
        4) 15_Chapter_15
39984000 42868000 2884000
                Tagging
        5) 16_Chapter_16
42868000 44614000 1746000
                Tagging
        6) 17_Epilog
44614000 45225000 611000
                Tagging
        7) 18_Afterword
45225000 45564000 339000
                Tagging
        8) 19_Authors_Note
45564000 33554430 -12009570
                Tagging
All Done

**Comment by crisbal** [comment]
Thanks for reporting the issue Paul, right now I am a bit busy with my university exams and I can get back to this issue starting from next week.

The thing that is scaring me a little bit is the `-12009570` for the duration of track 8 (I don't think it is an underflow/overflow of some sort but who knows).

If everything on my side is working correctly I will probably have to use another solution instead of pydub (I used pydub since it was the easiest solution out there, but probably just using "raw" ffmpeg would work better). 

Thanks for the detailed report and investigation, I will keep you updated as soon as I can.

**Comment by crisbal** [comment]
Hey there, some updates.

I am trying using raw ffmpeg (through `subprocess.call` or through some wrapper), it seems to kinda work, it would be great if you could give it a test with your file/setup.

Please use this branch https://github.com/crisbal/album-splitter/tree/ffmpeg-raw (`git checkout ffmpeg-raw; git pull origin ffmpeg-raw`), reinstall requirements (`pip install -r requirements/prod.txt`) and then use the same command as before (beware, some functionalities such as threaded execution and duration mode might be broken but I don't think you need them right now).

Let me know if everything works fine, I am especially worried about performance, from my tests sometimes the conversion would slow down a lot but in the end it completed.

**Comment by kamisori** [comment]
That works.
I dont know if it's faster or slower, but at least it works :D
ffmpeg is using ~12GB of RAM, but this was to be expected.

However, I expected the title tags of the split files to be equal to what i wrote in the tracks file, instead the tags of the original file's were applied to the split files.

**Comment by crisbal** [comment]
Oh yes, that is because I forgot to enable that feature. How long did it take?

**Comment by kamisori** [comment]
It took about one hour, the (very verbose [which I kinda like actually]) output ends with the following two lines:

size=    4372kB time=01:04:24.02 bitrate=   9.3kbits/s speed=3.44x
video:0kB audio:536996kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
All Done

"size" is actully for the first split file. But "time" seems to be the overall time it took.

**Comment by crisbal** [comment]
Hmm, I don't really work with files that big so I am not sure if that is a long time, I will investigate a bit.

**Comment by kamisori** [comment]
I guess you could use Audacity to create your very own silent album XD
My file was an audiobook though.
