### ISSUE TITLE
Add command parameter for custom bitrate

### ISSUE THREAD

**Issue by JoelLisenby** [crisbal/album-splitter#26]
By default it exports 128k quality mp3 which is pretty low quality.

https://github.com/crisbal/album-splitter/blob/f30633d9d2233a7ca8e787c29b52e4189ad79be2/utils/split_song.py#L10

It would be great if instead of having to modify the script you could add the bitrate as a command parameter when splitting a file.

I had to modify line 10 to:
`album[start:][:duration].export(track_path, bitrate="320k", format="mp3")`

**Comment by crisbal** [comment]
Fixed! I added the `-bitrate` option and by default it is 320k
