### ISSUE TITLE
Any success with this on OS X?

### ISSUE THREAD

**Issue by dhowe** [crisbal/album-splitter#28]
I'm getting the errors after installing requirements:

/path/youtube-dl-music/ydm: line 70: realpath: command not found
...
Error: Output directory "MUSIC_FOLDER" does not exist or is not a directory.

**Comment by dhowe** [comment]
I was able to get this to run by installing an [osx version of realpath](https://github.com/harto/realpath-osx) and then specifying a MUSIC_FOLDER in the .config, but then get more errors:

ERROR: Error while running command /usr/local/bin/ffmpeg -y -nostdin -i '/path/music-download.webm' -filter_complex '[0:0]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.15:measured_i=-17.98:measured_lra=16.1:measured_tp=0.12:measured_thresh=-28.81:linear=true:print_format=json[norm0]' -map_metadata 0 -map_metadata:s:a:0 0:s:a:0 -map_chapters 0 -c:v copy -map '[norm0]' -c:a libfdk_aac -b:a 201k -c:s copy /var/folders/w5/9kg3d9h93rz3ks72r74wbb_r0000gn/T/tsfkbfht.m4a! Error: Error running command ['/usr/local/bin/ffmpeg', '-y', '-nostdin', '-i', ''/path/music-download.', '-filter_complex', '[0:0]loudnorm=i=-23.0:lra=7.0:tp=-2.0:offset=0.15:measured_i=-17.98:measured_lra=16.1:measured_tp=0.12:measured_thresh=-28.81:linear=true:print_format=json[norm0]', '-map_metadata', '0', '-map_metadata:s:a:0', '0:s:a:0', '-map_chapters', '0', '-c:v', 'copy', '-map', '[norm0]', '-c:a', 'libfdk_aac', '-b:a', '201k', '-c:s', 'copy', '/var/folders/w5/9kg3d9h93rz3ks72r74wbb_r0000gn/T/tsfkbfht.m4a']: ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers
built with Apple clang version 11.0.3 (clang-1103.0.32.62)
configuration: --prefix=/usr/local/Cellar/ffmpeg/4.3.1 --enable-shared --enable-pthreads --enable-version3 --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-ffplay --enable-gnutls --enable-gpl --enable-libaom --enable-libbluray --enable-libdav1d --enable-libmp3lame --enable-libopus --enable-librav1e --enable-librubberband --enable-libsnappy --enable-libsrt --enable-libtesseract --enable-libtheora --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxml2 --enable-libxvid --enable-lzma --enable-libfontconfig --enable-libfreetype --enable-frei0r --enable-libass --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-librtmp --enable-libspeex --enable-libsoxr --enable-videotoolbox --disable-libjack --disable-indev=jack
libavutil      56. 51.100 / 56. 51.100
libavcodec     58. 91.100 / 58. 91.100
libavformat    58. 45.100 / 58. 45.100
libavdevice    58. 10.100 / 58. 10.100
libavfilter     7. 85.100 /  7. 85.100
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  7.100 /  5.  7.100
libswresample   3.  7.100 /  3.  7.100
libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from ''/path/music-download.':
Metadata:
encoder         : google/video-file
Duration: 00:44:33.20, start: -0.007000, bitrate: 134 kb/s
Stream #0:0(eng): Audio: opus, 48000 Hz, stereo, fltp (default)
Unknown encoder 'libfdk_aac'
Bitrate: 201kbps

**Comment by crisbal** [comment]
Hello @dhowe 

I probably need more context on this issue. What is `-/path/youtube-dl-music/ydm`?

Also from the output you might solve it by installing libfdk_aac (https://stackoverflow.com/questions/21553286/error-libfdk-aac-must-be-installed).

I don't have a Mac unfortunately so I can't try it there.

**Comment by dhowe** [comment]
The is the path where I cloned the repo. In any case, the first problem for OS X is that 'realpath' doesn't exist, at least not by default. After installing 'libfdk_aac', I still get that it is an 'Unknown encoder'. But the actual error is b/c of the missing file: '/path/to/Music/Artist - Album-normalized.m4a'. Is this due to the encoding failure?

```
mv: rename /path/to/Music/Artist - Album-normalized.m4a to /path/to/Music/Artist - Album.m4a: No such file or directory
Adding metadata.
Error: File '/path/to/Music/Artist - Album.m4a' does not exist.
```
