### ISSUE TITLE
Apparent TypeError

### ISSUE THREAD

**Issue by Sir-Matthias** [crisbal/album-splitter#39]
I'm completely new to this area of coding and programming (and github too for that matter), so I think something went wrong with the install. Anyway, I keep getting this error here:

> (venv) C:\project\album-splitter>python -m album_splitter --file "C:/BachArias.mp3"
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\project\album-splitter\album_splitter\__main__.py", line 9, in <module>
    from .tag_file import tag_file
  File "C:\project\album-splitter\album_splitter\tag_file.py", line 5, in <module>
    def tag_file(file: Path, tag_data: dict[str, str]):
TypeError: 'type' object is not subscriptable

Not sure what I'm doing wrong, and it's probably a stupid mistake I made somewhere, but I have no clue where to start. Thanks in advance for any help.
P.S. Also, I don't think I formatted this right, but the insert code tab seemed worse than the quote.

**Comment by crisbal** [comment]
Hello, I should have fixed this now. Please, re-download the repository (or use `git pull` if you obtained it with `git clone`) and try again  from scratch.
