### ISSUE TITLE
Can't use Hangul

### ISSUE THREAD

**Issue by x9cf9w73cv7y** [crisbal/album-splitter#40]
It is impossible to use a tracklist with Korean characters.
```
Reading tracks file
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\lol\album-splitter\album_splitter\__main__.py", line 119, in <module>
    tracks_content = tracks_file.read_text()
  File "C:\Python39\lib\pathlib.py", line 1257, in read_text
    return f.read()
  File "C:\Python39\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 32: character maps to <undefined>
```

Steps to reproduce:
Using this tracklist
```
1. 00:00 Bobby Kim - Stranger (이방인)
2. 03:42 Lee Ki Chan - Going to Meet You Now (지금 만나러 가요) 
3. 07:46 Jun Hye Won (전혜원) - A Good Day Like This (이렇게 좋은 날)
4. 11:22 G.O - As If Tomorrow Won't Come (내일이 안 올 것처럼)
5. 15:12 Bang Min Ah - You and I (니가내가)
6. 18:01 Park Jung Ah - Because of You
```
and the command "python -m album_splitter -yt https://www.youtube.com/watch?v=FV5ahxcaBWo"

**Comment by crisbal** [comment]
Hello, I am taking a look at this now. Would you mind uploading your `tracks.txt` here? 

(I think it has something to do with the character encoding used to save the `tracks.txt` file).

To upload it, simply drag the file and drop it into the text box for the reply, or click here:

![image](https://user-images.githubusercontent.com/2728038/120896550-62943580-c622-11eb-805f-1fcdfb6225b4.png)

**Comment by x9cf9w73cv7y** [comment]
[tracks.txt](https://github.com/crisbal/album-splitter/files/6602772/tracks.txt)

**Comment by crisbal** [comment]
Thanks. I should have pushed an attempt to fix the issue. 

Could you please update the code (either by redownloading and reinstalling the project, or by using `git pull origin master`) and see if this works for you?

**Comment by x9cf9w73cv7y** [comment]
Thank you. It works now without problems.

**Comment by crisbal** [comment]
Great, perfect!
