### ISSUE TITLE
Attribute Error

### ISSUE THREAD

**Issue by Gabriel-Rodrigues-Gomes** [crisbal/album-splitter#46]
Reading tracks file
Found the following tracks:
        Heliacal Rising - 0:00:00
        The First Point of Aries - 0:08:50
        Constellation Hipparchia - 0:18:13
        Occultated Temporal Dimensions - 0:30:42
        Aether Wind - 0:42:06
Splitting into files... (this could take a while)
Traceback (most recent call last):
  File "D:\Python\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\albumsplit\album-splitter\album_splitter\__main__.py", line 184, in <module>
    output_files = split_file(input_file, tracks, outfolder, output_format=str(input_file).split(".")[-1])
  File "D:\albumsplit\album-splitter\album_splitter\split_file.py", line 10, in split_file
    duration_command = ffmpy.FFprobe(
AttributeError: module 'ffmpy' has no attribute 'FFprobe'

**Comment by crisbal** [comment]
Hello Gabriel, 
this looks strange to me. Let's try to get some more context on the issue, if you want.

What is the ouput of the following commands?

* python --version
* python3 --version
* pip freeze
* where.exe python
* where.exe python3
* ffmpeg.exe -version 
* ffprobe.exe -version

Thanks!
