### ISSUE TITLE
Easier way to edit tracks.txt format?

### ISSUE THREAD

**Issue by crisbal** [crisbal/Album-Splitter#5]
As title. 

I am open to suggestions.

**Comment by Lightning3105** [comment]
Not directly related, but the ability to specify more tags within tracks.txt would be nice. For example:
`<start-time> - <title> - <artist> - <album> - <etc...>`

**Comment by Lightning3105** [comment]
I created a simple GUI for the program, it has the option to reformat a user's tracklist into one that can be used by the program. Pull request: #11.

**Comment by crisbal** [comment]
Fixed in #15
