### ISSUE TITLE
Module distribution (single file) or package

### ISSUE THREAD

**Issue by surrealcristian** [crisbal/album-splitter#7]
Are you interested in transform the project to a single file (module) or a package?

**Comment by crisbal** [comment]
I don't think a single file is that good but I am interested in making the whole thing a single package. I think the code should be refractored a bit, making new methods and fixing stuff.

**Comment by surrealcristian** [comment]
If you want, tell me when you consider the code ready to accept contributions.
I am interested in contribute in my spare time.

**Comment by crisbal** [comment]
There are a few things that need to be done like #5 and #4 

After that we could start adding new stuff and improving existing things. 

It would be cool to have some better way to implement information/tracklist providers (right now I manually check for flags if I need to use Wikipedia or file or amazon). My dream would be to have some kind of plugin system and each one could write plugins that tell the program where to get album info (such as track names, duration,...)
