### ISSUE TITLE
Upload to pypi

### ISSUE THREAD

**Issue by surrealcristian** [crisbal/album-splitter#8]
Are you interested in upload the project to pypi?

**Comment by crisbal** [comment]
I never done it. Does it allow to make the script installable via pip? If so I will upload the repo to pypi.

**Comment by surrealcristian** [comment]
Yes, it allow to make the script installable.

If you want, you can use https://github.com/surrealists/memecli/blob/master/setup.py as a base.

As result, you will can do something like:

pip install album-splitter

**Comment by crisbal** [comment]
Thanks I will look into that in the following days, unless you want to do it :)

But I'd like to try that myself.

**Comment by crisbal** [comment]
It took 7 years but we did it!
